import type { Metadata } from "next";
import "./globals.css";
import { balooDa2 } from "@/utils/fonts";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarWrapper from "@/components/sidebar/SidebarWrapper";
import { ThemeProvider } from "./providers";
import { User } from "@/utils/types";
import { getAuthor, getResume, getTopProjects } from "@/utils/actions";
import Navbar from "@/components/mobile-navigation/Navbar";

export const metadata: Metadata = {
  title: "Anurag Choudhury | Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const author: User = await getAuthor();
  const topProjects = await getTopProjects({ limit: 3 });
  const resume = await getResume();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${balooDa2.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={false}>
            <SidebarWrapper
              author={author}
              topProjects={topProjects}
              resume={resume}
            />
            <main className="w-full">
              <Navbar author={author} resume={resume} />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
